#!/usr/bin/env bash

BAUD=115200
AVR_GDB='/home/cgn/prog/external/avr-gdb/avr-gdb/bin/avr-gdb'


if [[ $# -ne 1 ]]; then
  echo "Please supply a parameter of {build, flash, sim, debug, rebuild-container, generate-compile-commands, clean}."
  exit
fi

uP="atmega2560"

case $1 in
  scons)
    # podman run -it --rm --mount type=bind,source=$PWD/src,target=/build avr_docker
    cd src
    scons baud=$BAUD debug
    cd ../
    avr-size --mcu=$uP -C src/simplos.out
    ;;
  build)
    #podman run -it --rm --mount type=bind,source=$PWD/src,target=/build avr_docker
    cd src
    scons baud=$BAUD
    cd ../
    avr-size --mcu=$uP -C src/simplos.out
    ;;

  flash)
    #podman run -it --rm --mount type=bind,source=$PWD/src,target=/build avr_docker
    cd src
    BAUD=115200
    scons baud=$BAUD
    cd ../

    avr-size --mcu=$uP -C src/simplos.out
    avr-objcopy -O ihex -R .eeprom src/simplos.out out.hex
    # avrdude -C /usr/share/arduino/hardware/tools/avrdude.conf -c wiring \
    avrdude -c wiring \
      -p $uP \
      -D -P /dev/ttyUSB0 \
      -b $BAUD \
      -U flash:w:out.hex \
      /
          ;;

        sim)
          # podman run -it --rm --mount type=bind,source=$PWD/src,target=/build avr_docker
          cd src
          scons baud=$BAUD debug=1
          cd ../
          avr-size --mcu=$uP -C src/simplos.out
          simavr -g -m $uP src/simplos.out
          ;;

        debug)
          #podman run -it --rm --mount type=bind,source=$PWD/src,target=/build avr_docker avr-gdb src/simplos.out -ex "target remote :1234" -ex "directory src/"
          ${AVR_GDB} src/simplos.out -ex "target remote :1234" -ex "directory src/"
          ;;

        rebuild-container)
          podman build --rm -t avr_docker \
            --build-arg USER_ID=$(id -u) \
            --build-arg GROUP_ID=$(id -g) .
                      ;;

                    generate-compile-commands)
                      echo "generating compile_commands.json"
                      scons -c
                      scons baud=115200 debug=1 --compiledb=
                      ;;


                    clean)
                      rm -f src/*.o
                      rm -f src/*.hex
                      rm src/simplos
                      ;;

                    esac
